const wchar_t* z_strings[] = { L"",L"App1",
L"No",
L"Yes",
L"OK",
L"Cancel",
L"Light/Dark",
L"New",
L"Open",
L"Save",
L"Save as...",
L"Exit",
L"Default",
L"Light",
L"Dark",
L"Restart application to apply.",
L"Help",
L"File",
L"Export",
L"XAML",
L"Insert",
L"File",
L"Menu Root",
L"Select",
L"Delete",
L"Edit",
L"Undo",
L"Redo",
L"Run (with Title Bar)",
L"Hello there",
L"About",
L"You must first select a Panel, a NavigationView or a ContentControl with no children.",
L"You must first add a Panel or a NavigationView.",
L"Filter",
L"Save changes?",
L"XAML copied to clipboard.",
L"Cannot delete root element.",
L"Select all children",
L"Unselect all children",
L"Add item",
L"Add separator",
L"Delete item",
L"Menu",
L"Test menu",
L"Load",
L"Menu name",
L"Templates",
L"Standard File/Edit/View/Help",
L"(None)",
L"Label",
L"Separator",
L"Add submenu",
L"Radio button group",
L"Menu Hierarchy",
L"Properties",
L"Panels",
L"Controls",
L"View",
L"Elements",
L"TreeView Based Item List",
L"Select Button Item List",
L"Run (without Title Bar)",
L"Clear",
L"Page Save",
L"Page Load",
L"Page Delete",
L"Page name",
L"This item can only be added to a NavigationView.",
L"Start here. Add a panel to your design. Start with the most common, a Grid.",
L"You can select any item here and below there are its properties. The last item inserted is automatically selected.",
L"Run (ContentDialog)",
L"Build",
L"View C++ code sample",
L"You must first save a design as a Page to load it here.",
L"You must create a menu using the menu creator to load it here.",
L"Due to a bug in WebView2 it's not automatically resized.",
L"Show code",
L"Callable function for %s event",
L"// Element is clicked",
L"This is a binding property",
L"Copy",
L"Test file dialog",
};

#define MAX_LANG 81

