import "FileSystemItem.idl";
import "Item.idl";

namespace VisualWinUI3
{
    [default_interface]
    runtimeclass FileDialog : Microsoft.UI.Xaml.Window,Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        FileDialog();

    IInspectable CurrentPath;
    Windows.Foundation.Collections.IObservableVector<VisualWinUI3.Item> BreadcrumbBarItems{ get; };
    Windows.Foundation.Collections.IObservableVector<VisualWinUI3.FileSystemItem> TreeItems{ get; };
    Windows.Foundation.Collections.IObservableVector<VisualWinUI3.Item> FileItemsX{ get; };


    }
}
