import "Item.idl";

namespace VisualWinUI3
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainPage();
        static String txt(Int32 sidx);
        void Refresh();
        void Refresh2(String str);
		Int64 wnd;
        Int64 ProjectPtr{ get; };
        String CurrentFilter;
		void ApplyTopProperties();
        Windows.Foundation.Collections.IObservableVector<Item> PropertyItems{ get; };
		Microsoft.UI.Xaml.Controls.DataTemplateSelector PropertyTypeSelector{ get; };

    }
}
